### ISSUE TITLE
Keyboard hides UITextField.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [MarioIannotta/PullUpController#1]
Thanks for this wonderful library.

When the `Keyboard` is open, is there any way to keep up the `UITextField/UITextView`?

**Comment by MarioIannotta** [comment]
Hi Rashesh,  
I don't think I have full understood your problem here but basically you could observe the `UIKeyboardWillHide` and `UIKeyboardWillShow` notifications and move the `PullUpController` accordingly using the method `pullUpControllerMoveToVisiblePoint(_ visiblePoint: CGFloat, completion: (() -> Void)?)`

Does this could help you solve your problem?

Cheers,
Mario.

**Comment by Rashesh-Bosamiya** [comment]
Yes, Thanks! 😊
