### ISSUE TITLE
current position property

### ISSUE THREAD

**Issue by idanboa** [MarioIannotta/PullUpController#13]
i need to know the current position of the top of the drawer in order to move elements around in the containing viewController.
i would use the origin of the PullUpController frame.. but this seems hacky and i need observation on this value for real time changes.
also i can't access `topConstraint`.

i suggest adding a public function `pullUpControllerTopPositionChangedTo(_ position: CGFloat)` after changes to `topConstraint` are made.

Edit:
i can see that this was merged to the repo but reverted in https://github.com/MarioIannotta/PullUpController/pull/7 
why was this feature removed?

**Comment by MarioIannotta** [comment]
Hi @idanboa 
the PR you mentioned was reverted because the same functionality has been integrated with [this PR](https://github.com/MarioIannotta/PullUpController/pull/6) in a more _swifty_ way.
But I guess that what you need is a little bit different.
I've added the closure
```
/**
  The closure to execute when the view controller's view is dragged.
  The point, expressed in the pull up controller parent coordinate system, is provided in the closure parameter.
*/
open var onDrag: ((_ point: CGFloat) -> Void)?
``` 
on the [develop](https://github.com/MarioIannotta/PullUpController/tree/develop) branch.

Could you please check if that works for you?
Thanks,
Mario

**Comment by idanboa** [comment]
Hi, thanks for the response 👍.
this is a good start, but shouldn't this value be representing the top position at all times and not just on drag? there is an option to animate positions programmatically that this closure is not called for, basically every time a change is made to `topConstraint?.constant`. why not have a unified block that notifies all movements?

Disclosure: i am currently working with a forked version of the library to accommodate for special cases in my app 😊

**Comment by MarioIannotta** [comment]
I thought about that but then I was wondering: when you would like to be notified while changing the position programmatically? At the beginning of the animation or at the end? 
Since we already have
- `open var willMoveToStickyPoint: ((_ point: CGFloat) -> Void)?`
- `open var didMoveToStickyPoint: ((_ point: CGFloat) -> Void)?`

to handle those actions so you just need a closure that notify you when the user is dragging the controller's view.

That's the best solution I could think to handle your use case whilst keeping the apis clean and simple, if you have a better idea PRs are always welcome :)
