### ISSUE TITLE
PullUpController with UITableViewController

### ISSUE THREAD

**Issue by tomaculum** [MarioIannotta/PullUpController#14]
Hi,

I encountered a problem after replacing the MapView of the example with a TableViewController:
[https://vimeo.com/278366283](https://vimeo.com/278366283)

I forked it and uploaded my code changes here: [https://github.com/tomaculum/PullUpController](https://github.com/tomaculum/PullUpController)

My TableViewController is still in the [MapViewController](https://github.com/tomaculum/PullUpController/blob/master/Example/PullUpController/UI/MapViewController.swift) file.

Is this an expected error which will occur with every scroll view as view controller or is this my fault and there is an issue in my implementation of the TableViewController?

**Comment by MarioIannotta** [comment]
Hi @tomaculum 
the problem with your code is that the `view` property for a `UITableViewController` is a `UITableView` and not an `UIView`. 
This property is used in `UIViewController.addPullUpController(_ pullUpController: PullUpController)` to add the pull up controller's view to the view hierarchy therefore adding a view to an `UITableView` cause the first one to scroll with the table view.

To solve your problem just use a simple `UIViewController`, add an `UITableView` and everything will work like [in this example](https://github.com/MarioIannotta/PullUpController/files/2164172/PullUpController-master.zip).

Thanks a lot for pointing that out (i rarely use `UITableViewController` that's why I never encountered the issue) but I'm afraid that's not solvable (at least right now I don't have ideas :)).

I think I'll add an assert (or a log) in the next release linking this issue.

Thanks,
Mario.

**Comment by tomaculum** [comment]
Hi Mario,
Thank you very much for your explanation and the corrected code sample!

I guess it would be enough to add the first paragraph of your answer somewhere to the README. The UI issues are so obvious that they will either read the README again or find this issue by themselves.

**Comment by MarioIannotta** [comment]
Fixed with https://github.com/MarioIannotta/PullUpController/commit/0c866ab93cd8c783545d10202cf86c0e1232ca30
