### ISSUE TITLE
Close controller with drag swipe

### ISSUE THREAD

**Issue by fixique** [MarioIannotta/PullUpController#24]
It would be very cool if you add the ability to close the controller by strongly swiping down.

Thx for great library)

**Comment by MarioIannotta** [comment]
Hi @fixique I got what you're talking about and we have a very similar check that maybe we could improve. 
Basically here if the user is scrolling "fast" we skip to the next sticky point. https://github.com/MarioIannotta/PullUpController/blob/50027c5848cca1a895bc27800489cda237f6470b/PullUpController/PullUpController.swift#L230

Everything should work fine if there're only 3 sticky points because if i'm at number 3 and I'm scrolling fast the pull up controller's view will be moved to the first sticky point. We could have some problems when the number of sticky points is > 3.

A solution could be
1. let the developer customize the "fast scrolling threshold" so we can remove that very ugly hardcoded `700`
2. let the developer specify a "faster scrolling threshold", beyond which the pull up controller's view will be fully contracted (if the user is scrolling down) or expanded (if the user is scrolling up)

What do you think?
Is that going to solve your problem?

**Comment by fixique** [comment]
Hi @MarioIannotta sorry for really long replay. I think you didn't quite understand what I meant. I meant the opportunity to remove PullUpController from parent view controller by strong swipe down. 

Now I can only present PullUpController and swipe down to some sticky point. 

I solve my problem with some not beautiful code. I show it below:

1. First of all add 3 sticky points for present PullUpController. 
a. 0.0 point
b. some first preview point (example 150.0)
c. some full preview point (example 350.0)
2. I am use didMoveToStickyPoint completion block for detect if we goes to 0.0 point and now PullUpController should be remove from parentViewController.
3. I am call method        ` self.parentViewController.removePullUpController(self, animated: false)` 

But I think that will be great if you add some ability for just turn on this feature by default.

Thank you for you replay. Maybe I will create pull request with this ability later, if you do not mind)

**Comment by MarioIannotta** [comment]
Ok, your issue is clear now.
I think part of the previous solution is still valid, I can expose a "dismissDragThresholdVelocity" beyond which the controller's view will be hidden and removed from the superview.

What do you think?

**Comment by fixique** [comment]
Yes, I think this will be great. If you give me a chance I can try to do this. What do you think?)

**Comment by MarioIannotta** [comment]
Enjoy ;)
