### ISSUE TITLE
How Do I use "onDrag" in version 0.6.0?

### ISSUE THREAD

**Issue by jayarajb1116** [MarioIannotta/PullUpController#51]

**Comment by MarioIannotta** [comment]
In 0.6.0, instead of using the closures `willMoveToStickyPoint`, `didMoveToStickyPoint` and`onDrag` you should override the methods  override func `pullUpControllerWillMove(to stickyPoint: CGFloat)` `pullUpControllerDidMove(to stickyPoint: CGFloat)` and `pullUpControllerDidDrag(to point: CGFloat)`
For more informations you can check this commit https://github.com/MarioIannotta/PullUpController/commit/4ceffcae014b24dfb0b04ca2749ee4676ad41b1e
