### ISSUE TITLE
Initial offset for iphone X is a bit buggy

### ISSUE THREAD

**Issue by serdar333** [MarioIannotta/PullUpController#57]
iPhone X
![Simulator Screen Shot - iPhone Xʀ - 2019-04-19 at 15 59 31](https://user-images.githubusercontent.com/22591979/56425265-22479100-62bc-11e9-9ae1-39048754ddcb.png)

Others
![Simulator Screen Shot - iPhone 6 - 2019-04-19 at 16 00 33](https://user-images.githubusercontent.com/22591979/56425303-4f943f00-62bc-11e9-95f7-6e4e388425e9.png)

**Comment by himanshuNetsol** [comment]
Facing the same issue ... Any solution pls??

**Comment by MarioIannotta** [comment]
It's an issue of the demo app rather than an issue of the library itself due to the fact that in `SearchViewController`, the `Visual Effect View` is pinned to the safe area bottom constraint.

If you want to fix that, you should 
1. pin that view bottom to the superview bottom
2. embed the subview in a new view where the bottom is pinned to the safe area bottom
3. update the `pullUpControllerMiddleStickyPoints` accordingly.
