### ISSUE TITLE
Cannot embed pullupcontroller within tab bar view

### ISSUE THREAD

**Issue by hxsseeb** [MarioIannotta/PullUpController#66]
Contacted you on twitter have a replicated example on me, when a tab bar view is embed into the main view the pullupcontroller is hidden under the tab bar on the iPhone X, Xr, Xs and Xs Max

**Comment by MarioIannotta** [comment]
Hello @hxsseeb could you please attach the example project here?

**Comment by hxsseeb** [comment]
[Uploading PullUpController With ISSUE.zip…]()

**Comment by MarioIannotta** [comment]
I think you didn't wait for the upload to finish, can you please double check?

**Comment by hxsseeb** [comment]
[PullUpController With ISSUE.zip](https://github.com/MarioIannotta/PullUpController/files/3567137/PullUpController.With.ISSUE.zip)
 Here

**Comment by hxsseeb** [comment]
hey man. any luck?

**Comment by MarioIannotta** [comment]
Hey I did a little investigation and the problem is that the space of the bottom bar is never take into account in the calculations.
eg: [this line](https://github.com/MarioIannotta/PullUpController/blob/1b294293d7fe94dd59c7e93ee2ef9115be4d40c2/PullUpController/PullUpController.swift#L243)

I'm not planning to fixing that because it need too much time and the outcome would be not so good in terms of user experience.

Please consider to use the component in a controller where no other components are involved at the bottom of the screen.

**Comment by hxsseeb** [comment]
I see. Thank you none the less for looking into the issue. One other problem is that the PullUpController does not begin from the bottom of the screen on the iPhone X, Xr and Xs variants. How can this be solved?

**Comment by hxsseeb** [comment]
I see. Thank you none the less for looking into the issue. 

One other problem is that the PullUpController does not begin from the bottom of the screen on the iPhone X, Xr and Xs variants. 

How can this be solved?

Apologies if I'm asking a lot of questions, I am new to Swift programming and just really want to implement your pod into my project. 

Photo below:

![IMG_8ABBDFC5665D-1](https://user-images.githubusercontent.com/54819836/64359040-78189d80-cfff-11e9-8c4f-e586743e4eda.jpeg)

**Comment by MarioIannotta** [comment]
No worries at all :)
https://github.com/MarioIannotta/PullUpController/issues/57 here there's a solution for the issue you're reporting, let me know if it works for you.
